### ISSUE TITLE
The flow passing twice in dnd plugin creator

### ISSUE THREAD

**Issue by antherkiv** [bkniffler/draft-wysiwyg#9] opened 2016-05-31 15:40 UTC
Hello when I drop an image over the editor, this pass twice in dnd plugin creator, the second time without file and crash, I looking why now.

**Comment by bkniffler** [comment] 2016-06-01 08:28
Strange, I'm not able to reproduce this. Could you provide an error message or something, that would make it more easy to take care of it!

**Comment by Antherkiv** [comment] 2016-06-01 22:19
It's not related with draft-wysiwyg, it's related with a dependency that try to read the file content and convert to diferent formats (b64, etc), I think I have the wrong package, I'm sorry.

**Comment by antherkiv** [comment] 2016-06-03 16:49
![captura de pantalla 2016-06-03 a la s 11 51 15 a m](https://cloud.githubusercontent.com/assets/11079619/15786302/888f3f98-2981-11e6-8437-265c2ab384c8.png)
I found the problem for some reason when the code it's precompiled fails:

draft-js-plugins-dnd-plugin onDropFile onDropInnerFile function,
this piece of code it's the problem:

 var data = { files: [], formData: formData };
            for (var key in files) {
              if (files[key]) {
                data.formData.append('files', files[key]);
                data.files.push(files[key]);
               }

(The example doesn't fails because of that).

Then the function getIndexBy it's attached with files and when the flow it's on readFiles ( because it's not a file readFile function fails  and the promise never resolve).

I'm sorry I don't have too much free time.

**Comment by bkniffler** [comment] 2016-06-12 10:13
Sorry for the extended abscence. I see the problem now, though I still wasn't able to reproduce it. I've added a check:

``` js
if (files[key] && files[key] instanceof File)
```

This should fix the problem for you, but I'm not sure why it gets called 2 times in the first place.

I'm closing this, but if you still got an issue with that, feel free to re-open it!

**Closed as completed by bkniffler** 2016-06-12 10:13 UTC
